apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: locations
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: locations
    spec:
      containers:
      - name: locations
        image: locations
        ports:
        - containerPort: 3001
